/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms;

import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class Librarysection extends javax.swing.JFrame {

    /**
     * Creates new form Librarysection
     */
    public Librarysection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Addbooks = new javax.swing.JButton();
        Viewbooks = new javax.swing.JButton();
        Deletebooks = new javax.swing.JButton();
        Issuebooks = new javax.swing.JButton();
        Viewissuedbooks = new javax.swing.JButton();
        Returnbooks = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Addbooks.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Addbooks.setText("Add books");
        Addbooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbooksActionPerformed(evt);
            }
        });
        getContentPane().add(Addbooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 210, 40));

        Viewbooks.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Viewbooks.setText("View books");
        Viewbooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewbooksActionPerformed(evt);
            }
        });
        getContentPane().add(Viewbooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 210, -1));

        Deletebooks.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Deletebooks.setText("Delete books");
        Deletebooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebooksActionPerformed(evt);
            }
        });
        getContentPane().add(Deletebooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 210, -1));

        Issuebooks.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Issuebooks.setText("Issue books");
        Issuebooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssuebooksActionPerformed(evt);
            }
        });
        getContentPane().add(Issuebooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 220, -1));

        Viewissuedbooks.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Viewissuedbooks.setText("View issued books");
        Viewissuedbooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewissuedbooksActionPerformed(evt);
            }
        });
        getContentPane().add(Viewissuedbooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 220, -1));

        Returnbooks.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Returnbooks.setText("Return books");
        Returnbooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnbooksActionPerformed(evt);
            }
        });
        getContentPane().add(Returnbooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 220, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 500, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 170));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/2pg.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewbooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewbooksActionPerformed
        // TODO add your handling code here:
       
                                 setVisible(false);
				Viewbooks a= new Viewbooks();
				a.setVisible(true);
    }//GEN-LAST:event_ViewbooksActionPerformed

    private void DeletebooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebooksActionPerformed
        // TODO add your handling code here:
        
                                setVisible(false);
				Deletebooks a= new Deletebooks();
				a.setVisible(true);
    }//GEN-LAST:event_DeletebooksActionPerformed

    private void AddbooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbooksActionPerformed
        // TODO add your handling code here:
      
                                setVisible(false);
				Addbooks a= new Addbooks();
				a.setVisible(true);
    }//GEN-LAST:event_AddbooksActionPerformed

    private void ViewissuedbooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewissuedbooksActionPerformed
        // TODO add your handling code here:
      
                                setVisible(false);
				Viewissuedbooks a= new Viewissuedbooks();
				a.setVisible(true);
        
        
    }//GEN-LAST:event_ViewissuedbooksActionPerformed

    private void IssuebooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssuebooksActionPerformed
        // TODO add your handling code here:
        
                                setVisible(false);
				Issuebooks a= new Issuebooks();
				a.setVisible(true);
    }//GEN-LAST:event_IssuebooksActionPerformed

    private void ReturnbooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnbooksActionPerformed
        // TODO add your handling code here:
        
                                setVisible(false);
				Returnbook a= new Returnbook();
				a.setVisible(true);
    }//GEN-LAST:event_ReturnbooksActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Librarylogin a = new Librarylogin();
        a.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Librarysection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Librarysection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Librarysection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Librarysection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Librarysection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbooks;
    private javax.swing.JButton Deletebooks;
    private javax.swing.JButton Issuebooks;
    private javax.swing.JButton Returnbooks;
    private javax.swing.JButton Viewbooks;
    private javax.swing.JButton Viewissuedbooks;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
